repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: debug-statements
          - id: requirements-txt-fixer
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.0.1
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.4
      hooks:
          - id: pyupgrade
            args: [--py36-plus]