version: '3.8'

services:
  alita:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alita
    depends_on:
      - mongodb
      - redis
    environment:
     - DOPPLER_TOKEN

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alita_beta_robot
      - MONGO_INITDB_ROOT_PASSWORD=alita_beta_robot
      - MONGO_INITDB_DATABASE=alita_beta_robot
    command: mongod

  redis:
    image: redis:alpine
    container_name: redis
    environment:
      - REDIS_PASSWORD=root
