[tool.poetry]
name = "Alita_Robot"
version = "0.4.3"
description = "Alita is a Telegram Group managment bot made using Pyrogram and Python, fully asynchronous."
authors = ["Divkix <techdroidroot@gmail.com>"]
license = "GNU AGPL v3.0"

[tool.poetry.dependencies]
python = "^3.7"
pyrogram = "^1.1.13"
TgCrypto = "^1.2.2"
asyncio = "^3.4.3"
psycopg2-binary = "^2.8.6"
SQLAlchemy = "^1.3.23"
requests = "^2.25.1"
speedtest-cli = "^2.1.2"
googletrans = "^3.0.0"
tswift = "^0.7.0"
regex = "^2020.11.13"
pynewtonmath = "^1.0.1"
wikipedia = "^1.4.0"
redis = "^3.5.3"
python-dateutil = "^2.8.1"
aiohttp = "^3.7.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
